CREATE TABLE respostas_prep (
    id SERIAL PRIMARY KEY,
    ts_utc TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    versao_form TEXT,
    conhecimento_prep TEXT,
    conhecimento_pep TEXT,
    acesso_servicos TEXT,
    fonte_informacao TEXT,
    uso_preppep TEXT,
    conhece_usuarios TEXT,
    teste_hiv_freq TEXT,
    metodos_prevencao TEXT,
    genero TEXT,
    orientacao_sexual TEXT,
    raca TEXT,
    faixa_etaria TEXT,
    escolaridade TEXT,
    renda TEXT,
    regiao TEXT,
    subprefeitura TEXT,
    comentarios TEXT
);